media:
  input: static/img
  output: static/img
content:
  - name: blog
    label: Blog Posts
    type: collection
    path: blog
    view:
      fields: [ title, published, date ]
    fields:
      - name: published
        label: Published
        type: boolean
        default: true
      - name: date
        label: Date
        type: date
      - name: title
        label: Title
        type: string
      - name: body
        label: Body
        type: rich-text
  - name: config
    label: Site Configurations
    type: file
    path: docusaurus.config.js
    icon: settings-2
  - name: projects
    label: Projects
    type: file
    path: src/components/Projects.tsx
    icon: square-kanban
  - name: knowledge-knox
    label: Knowledge Knox
    type: file
    path: content/knowledge-knox
    icon: lightbulb
    