media:
  input: static/img
  output: static/img
content:
  - name: blog
    label: Blog Posts
    path: blog
    type: collection
    view:
      fields: [ title, published, date ]
    fields:
      - name: published
        label: Published
        type: boolean
        default: true
      - name: date
        label: Date
        type: date
      - name: title
        label: Title
        type: string
      - name: body
        label: Body
        type: rich-text
  - name: site
    label: Site settings
    path: docusaurus.config.js
    type: file
    fields:
      - name: title
        label: Website title
        type: string